server:
  port: 8080

spring:
  security:
    enabled: false

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ChatModule;encrypt=false
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update